// qrCodeIssue.ts
// This file documents and tests the QR code scanning issue

/**
 * Issue Analysis: QR Code Scanning Not Showing H5 Customer Interface
 * 
 * Problem: When scanning QR codes generated by the system, the H5 customer interface
 * is not appearing correctly.
 * 
 * Root Cause Analysis:
 * 1. QR codes are generated correctly with the right URL parameters
 * 2. The URL structure should be: http://domain.com?page=customer&id=[ROOM_ID]
 * 3. The App.tsx component should route to CustomerOrder when page=customer
 * 4. CustomerOrder should initialize with the correct tableId from the URL
 */

// Test cases for the QR code functionality
interface QRCodeTest {
  description: string;
  url: string;
  expectedPage: string;
  expectedTableId: string;
}

const testCases: QRCodeTest[] = [
  {
    description: 'Hotel room QR code',
    url: 'http://localhost:5173?page=customer&id=8201',
    expectedPage: 'customer',
    expectedTableId: '8201'
  },
  {
    description: 'Lobby QR code',
    url: 'http://localhost:5173?page=customer&id=LOBBY',
    expectedPage: 'customer',
    expectedTableId: 'LOBBY'
  },
  {
    description: 'KTV room QR code',
    url: 'http://localhost:5173?page=customer&id=KTV01',
    expectedPage: 'customer',
    expectedTableId: 'KTV01'
  }
];

// Function to simulate URL parameter parsing
function parseUrlParams(url: string): Record<string, string> {
  try {
    const urlObj = new URL(url);
    const params: Record<string, string> = {};
    urlObj.searchParams.forEach((value, key) => {
      params[key] = value;
    });
    return params;
  } catch (error) {
    console.error('Invalid URL:', url);
    return {};
  }
}

// Function to validate QR code routing
function validateQRRouting(testCase: QRCodeTest): boolean {
  const params = parseUrlParams(testCase.url);
  const page = params['page'];
  const id = params['id'];
  
  return page === testCase.expectedPage && id === testCase.expectedTableId;
}

// Run tests
console.log('QR Code Routing Tests:');
testCases.forEach((testCase, index) => {
  const result = validateQRRouting(testCase);
  console.log(`${index + 1}. ${testCase.description}: ${result ? 'PASS' : 'FAIL'}`);
  if (!result) {
    console.log(`   Expected page: ${testCase.expectedPage}, got: ${parseUrlParams(testCase.url)['page']}`);
    console.log(`   Expected id: ${testCase.expectedTableId}, got: ${parseUrlParams(testCase.url)['id']}`);
  }
});

/**
 * Potential Issues and Solutions:
 * 
 * 1. URL Parsing Issue:
 *    - The CustomerOrder component uses useEffect to parse URL parameters on mount
 *    - If the component is not mounted correctly, the parameters won't be parsed
 * 
 * 2. Routing Issue:
 *    - App.tsx determines which component to render based on URL parameters
 *    - If the routing logic is incorrect, CustomerOrder may not be rendered
 * 
 * 3. Component Mounting Issue:
 *    - The CustomerOrder component may have initialization issues
 *    - Check if all required props are passed correctly
 * 
 * 4. Environment Issue:
 *    - The QR code may be pointing to the wrong domain
 *    - Check if the QR code generator is using the correct base URL
 */

// Solution: Enhanced QR code generation with better error handling
function generateQRCodeUrl(basePath: string, page: string, id: string): string {
  try {
    const url = new URL(basePath);
    url.searchParams.set('page', page);
    url.searchParams.set('id', id);
    
    // Use the QR server API to generate the QR code
    const qrApiUrl = new URL('https://api.qrserver.com/v1/create-qr-code/');
    qrApiUrl.searchParams.set('size', '200x200');
    qrApiUrl.searchParams.set('data', url.toString());
    qrApiUrl.searchParams.set('color', 'ea580c'); // Brand color
    qrApiUrl.searchParams.set('bgcolor', 'ffffff');
    
    return qrApiUrl.toString();
  } catch (error) {
    console.error('Error generating QR code URL:', error);
    return ''; // Return empty string on error
  }
}

// Solution: Enhanced URL parameter parsing for CustomerOrder component
function initializeCustomerOrderParams(): { tableId: string; language: string } {
  try {
    const params = new URLSearchParams(window.location.search);
    const idParam = params.get('id');
    const langParam = params.get('lang');
    
    // Set table ID if provided, otherwise default to lobby
    const tableId = idParam || 'LOBBY';
    
    // Set language with fallback chain: URL param → Cookie → Default
    let language = 'zh-CN'; // Default
    if (langParam === 'fil' || langParam === 'zh-CN') {
      language = langParam;
    } else {
      // Check cookie for language preference
      const cookieLang = document.cookie
        .split('; ')
        .find(row => row.startsWith('language='))
        ?.split('=')[1];
        
      if (cookieLang === 'fil' || cookieLang === 'zh-CN') {
        language = cookieLang;
      }
    }
    
    return { tableId, language };
  } catch (error) {
    console.error('Error initializing CustomerOrder params:', error);
    return { tableId: 'LOBBY', language: 'zh-CN' }; // Safe defaults
  }
}

// Export for testing
export { 
  parseUrlParams, 
  validateQRRouting, 
  generateQRCodeUrl, 
  initializeCustomerOrderParams,
  testCases
};